BulkyBook/BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType create success!";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var categoryFromDb = _db.Categories.Find(id);
            var CoverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDbFirst);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType update success!";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var categoryFromDb = _db.Categories.Find(id);
            var CoverTypeFromDbFirst = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (CoverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDbFirst);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.CoverType.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "CoverType delete success!";
            return RedirectToAction("Index");



        }
    }
}

BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create CoverType</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        
        <div>
            <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary">
                Back to list
            </a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete CoverType</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control"/>
            
        </div>
        
        <div>
            <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary">
                Back to list
            </a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit CoverType</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All"></div>*@
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        
        <div>
            <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary">
                Back to list
            </a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}



<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">CoverType List</h2>
        </div>
        <div class="col-6 text-end" >
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New CoverType
            </a>
        </div>
    </div>
    <br /> <br />

<table class="table table-bordered table-striped" style="width : 100%" 
    <thead>
        <tr>
            <th>
                Category Name
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Name
                </td>
                
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary- mx-2"><i class="bi bi-pencil-square"></i>Edit</a>
                        <a asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash-fill"></i>Delete</a>
                    </div>
                    
                </td>
            </tr>
        }
    </tbody>
</table>

</div>